apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: home-energy
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true
    editable: true
